site_name: Knowledge Base
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    scheme: slate
    primary: black
    accent: amber

nav:
  - Home:
    - Mkdocs: index.md
    - Composer: composer.md
    - Disk: disk.md
    - Docker: docker.md
    - Docs: docs.md
    - Gnome: gnome.md
    - Htaccess: htaccess.md
    - Logs: logs.md
    - Http 2: http2.md
    - Images: images.md
    - Magento 1: magento1.md
    - MySQL: mysql.md
    - Network: network.md
    - Patch: patch.md
    - PDF: pdf.md
    - Performance: performance.md
    - PHP: php.md
    - PhpStorm: phpstorm.md
    - Raspberry Pi: raspberry-pi.md
    - Redis: redis.md
    - SSH: ssh.md
    - System: system.md
    - Xdebug: xdebug.md
  - Bash:
    - General: bash/general.md
    - FU: bash/fu.md
  - Ubuntu:
    - Misc: ubuntu/misc.md
  - Git:
    - Branch: git/branch.md
    - Config: git/config.md
    - Log: git/log.md
    - Diff: git/diff.md
    - Patch: git/patch.md
    - Stash: git/stash.md
    - Tag: git/tag.md
    - Misc: git/misc.md
    - Oh My Git: git/oh-my-git.md
  - Magento 2:
    - Install: magento-2/install.md
    - Configuration: magento-2/configuration.md
    - Bulk Actions: magento-2/bulk-actions.md
    - Cron: magento-2/cron.md
    - DB: magento-2/db.md
    - Layout: magento-2/layout.md
    - Misc: magento-2/misc.md
    - NG98: magento-2/ng98.md
    - UI: magento-2/ui.md

extra_css:
  - 'css/extra.css'

markdown_extensions:
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: _snippets
      check_paths: true
  - footnotes

extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: 'https://github.com/yutv'
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/YuriiTvardyi'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/in/yuriitvardyi/'
