site_name: Knowledge Base
theme:
  name: 'material'
#  name: null
#  custom_dir: 'mkdocs-material/material'
  language: en
  feature:
    tabs: true
  palette:
      primary: 'Teal'
      accent: 'Teal'

extra_css:
  - 'css/extra.css'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - footnotes

extra:
    social:
        - type: 'github'
          link: 'https://github.com/yutv'
        - type: 'twitter'
          link: 'https://twitter.com/YuriiTvardyi'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/in/yuriitvardyi/'
